<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\District;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        District::insert([
            ['id' => 1, 'label' => 'Ancuabe', 'province_id' => 1],
            ['id' => 2, 'label' => 'Balama', 'province_id' => 1],
            ['id' => 3, 'label' => 'Chiúre', 'province_id' => 1],
            ['id' => 4, 'label' => 'Ibo', 'province_id' => 1],
            ['id' => 5, 'label' => 'Macomia', 'province_id' => 1],
            ['id' => 6, 'label' => 'Mecúfi', 'province_id' => 1],
            ['id' => 7, 'label' => 'Meluco', 'province_id' => 1],
            ['id' => 8, 'label' => 'Metuge', 'province_id' => 1],
            ['id' => 9, 'label' => 'Mocímboa da Praia', 'province_id' => 1],
            ['id' => 10, 'label' => 'Montepuez', 'province_id' => 1],
            ['id' => 11, 'label' => 'Mueda', 'province_id' => 1],
            ['id' => 12, 'label' => 'Namuno', 'province_id' => 1],
            ['id' => 13, 'label' => 'Nangade', 'province_id' => 1],
            ['id' => 14, 'label' => 'Palma', 'province_id' => 1],
            ['id' => 15, 'label' => 'Pemba', 'province_id' => 1],
            ['id' => 16, 'label' => 'Quissanga', 'province_id' => 1],
            ['id' => 17, 'label' => 'Muidumbe', 'province_id' => 1],
            ['id' => 18, 'label' => 'Bilene', 'province_id' => 2],
            ['id' => 19, 'label' => 'Chibuto', 'province_id' => 2],
            ['id' => 20, 'label' => 'Chicualacuala', 'province_id' => 2],
            ['id' => 21, 'label' => 'Chigubo', 'province_id' => 2],
            ['id' => 22, 'label' => 'Chókwè', 'province_id' => 2],
            ['id' => 23, 'label' => 'Chongoene', 'province_id' => 2],
            ['id' => 24, 'label' => 'Guijá', 'province_id' => 2],
            ['id' => 25, 'label' => 'Limpopo', 'province_id' => 2],
            ['id' => 26, 'label' => 'Mabalane', 'province_id' => 2],
            ['id' => 27, 'label' => 'Manjacaze', 'province_id' => 2],
            ['id' => 28, 'label' => 'Mapai', 'province_id' => 2],
            ['id' => 29, 'label' => 'Massangena', 'province_id' => 2],
            ['id' => 30, 'label' => 'Massingir', 'province_id' => 2],
            ['id' => 31, 'label' => 'Xai-Xai', 'province_id' => 2],
            ['id' => 32, 'label' => 'Funhalouro', 'province_id' => 3],
            ['id' => 33, 'label' => 'Govuro', 'province_id' => 3],
            ['id' => 34, 'label' => 'Homoíne', 'province_id' => 3],
            ['id' => 35, 'label' => 'Inhambane', 'province_id' => 3],
            ['id' => 36, 'label' => 'Inharrime', 'province_id' => 3],
            ['id' => 37, 'label' => 'Inhassoro', 'province_id' => 3],
            ['id' => 38, 'label' => 'Jangamo', 'province_id' => 3],
            ['id' => 39, 'label' => 'Mabote', 'province_id' => 3],
            ['id' => 40, 'label' => 'Massinga', 'province_id' => 3],
            ['id' => 41, 'label' => 'Maxixe', 'province_id' => 3],
            ['id' => 42, 'label' => 'Morrumbene', 'province_id' => 3],
            ['id' => 43, 'label' => 'Panda', 'province_id' => 3],
            ['id' => 44, 'label' => 'Vilanculos', 'province_id' => 3],
            ['id' => 45, 'label' => 'Zavala', 'province_id' => 3],
            ['id' => 46, 'label' => 'Bárue', 'province_id' => 4],
            ['id' => 47, 'label' => 'Chimoio', 'province_id' => 4],
            ['id' => 48, 'label' => 'Gondola', 'province_id' => 4],
            ['id' => 49, 'label' => 'Guro', 'province_id' => 4],
            ['id' => 50, 'label' => 'Macate', 'province_id' => 4],
            ['id' => 51, 'label' => 'Machaze', 'province_id' => 4],
            ['id' => 52, 'label' => 'Macossa', 'province_id' => 4],
            ['id' => 53, 'label' => 'Manica', 'province_id' => 4],
            ['id' => 54, 'label' => 'Mossurize', 'province_id' => 4],
            ['id' => 55, 'label' => 'Sussundenga', 'province_id' => 4],
            ['id' => 56, 'label' => 'Tambara', 'province_id' => 4],
            ['id' => 57, 'label' => 'Vanduzi', 'province_id' => 4],
            ['id' => 58, 'label' => 'Boane', 'province_id' => 5],
            ['id' => 59, 'label' => 'Magude', 'province_id' => 5],
            ['id' => 60, 'label' => 'Manhiça', 'province_id' => 5],
            ['id' => 61, 'label' => 'Marracuene', 'province_id' => 5],
            ['id' => 62, 'label' => 'Matola', 'province_id' => 5],
            ['id' => 63, 'label' => 'Matutuíne', 'province_id' => 5],
            ['id' => 64, 'label' => 'Moamba', 'province_id' => 5],
            ['id' => 65, 'label' => 'Namaacha', 'province_id' => 5],
            ['id' => 66, 'label' => 'Angoche', 'province_id' => 6],
            ['id' => 67, 'label' => 'Eráti', 'province_id' => 6],
            ['id' => 68, 'label' => 'Ilha de Moçambique', 'province_id' => 6],
            ['id' => 69, 'label' => 'Lalaua', 'province_id' => 6],
            ['id' => 70, 'label' => 'Larde', 'province_id' => 6],
            ['id' => 71, 'label' => 'Liúpo', 'province_id' => 6],
            ['id' => 72, 'label' => 'Malema', 'province_id' => 6],
            ['id' => 73, 'label' => 'Meconta', 'province_id' => 6],
            ['id' => 74, 'label' => 'Mecubúri', 'province_id' => 6],
            ['id' => 75, 'label' => 'Memba', 'province_id' => 6],
            ['id' => 76, 'label' => 'Mogincual', 'province_id' => 6],
            ['id' => 77, 'label' => 'Mogovolas', 'province_id' => 6],
            ['id' => 78, 'label' => 'Moma', 'province_id' => 6],
            ['id' => 79, 'label' => 'Monapo', 'province_id' => 6],
            ['id' => 80, 'label' => 'Mossuril', 'province_id' => 6],
            ['id' => 81, 'label' => 'Muecate', 'province_id' => 6],
            ['id' => 82, 'label' => 'Murrupula', 'province_id' => 6],
            ['id' => 83, 'label' => 'Nacala-a-Velha', 'province_id' => 6],
            ['id' => 84, 'label' => 'Nacala Porto', 'province_id' => 6],
            ['id' => 85, 'label' => 'Nacarôa', 'province_id' => 6],
            ['id' => 86, 'label' => 'Nampula', 'province_id' => 6],
            ['id' => 87, 'label' => 'Rapale', 'province_id' => 6],
            ['id' => 88, 'label' => 'Ribaué', 'province_id' => 6],
            ['id' => 89, 'label' => 'Chimbonila', 'province_id' => 7],
            ['id' => 90, 'label' => 'Cuamba', 'province_id' => 7],
            ['id' => 91, 'label' => 'Lago', 'province_id' => 7],
            ['id' => 92, 'label' => 'Lichinga', 'province_id' => 7],
            ['id' => 93, 'label' => 'Majune', 'province_id' => 7],
            ['id' => 94, 'label' => 'Mandimba', 'province_id' => 7],
            ['id' => 95, 'label' => 'Marrupa', 'province_id' => 7],
            ['id' => 96, 'label' => 'Maúa', 'province_id' => 7],
            ['id' => 97, 'label' => 'Mavago', 'province_id' => 7],
            ['id' => 98, 'label' => 'Mecanhelas', 'province_id' => 7],
            ['id' => 99, 'label' => 'Mecula', 'province_id' => 7],
            ['id' => 100, 'label' => 'Metarica', 'province_id' => 7],
            ['id' => 101, 'label' => 'Muembe', 'province_id' => 7],
            ['id' => 102, 'label' => 'N\'gauma', 'province_id' => 7],
            ['id' => 103, 'label' => 'Nipepe', 'province_id' => 7],
            ['id' => 104, 'label' => 'Sanga', 'province_id' => 7],
            ['id' => 105, 'label' => 'Beira', 'province_id' => 8],
            ['id' => 106, 'label' => 'Búzi', 'province_id' => 8],
            ['id' => 107, 'label' => 'Caia', 'province_id' => 8],
            ['id' => 108, 'label' => 'Chemba', 'province_id' => 8],
            ['id' => 109, 'label' => 'Cheringoma', 'province_id' => 8],
            ['id' => 110, 'label' => 'Chibabava', 'province_id' => 8],
            ['id' => 111, 'label' => 'Dondo', 'province_id' => 8],
            ['id' => 112, 'label' => 'Gorongosa', 'province_id' => 8],
            ['id' => 113, 'label' => 'Machanga', 'province_id' => 8],
            ['id' => 114, 'label' => 'Maringué', 'province_id' => 8],
            ['id' => 115, 'label' => 'Marromeu', 'province_id' => 8],
            ['id' => 116, 'label' => 'Muanza', 'province_id' => 8],
            ['id' => 117, 'label' => 'Nhamatanda', 'province_id' => 8],
            ['id' => 118, 'label' => 'Angónia', 'province_id' => 9],
            ['id' => 119, 'label' => 'Cahora-Bassa', 'province_id' => 9],
            ['id' => 120, 'label' => 'Changara', 'province_id' => 9],
            ['id' => 121, 'label' => 'Chifunde', 'province_id' => 9],
            ['id' => 122, 'label' => 'Chiuta', 'province_id' => 9],
            ['id' => 123, 'label' => 'Dôa', 'province_id' => 9],
            ['id' => 124, 'label' => 'Macanga', 'province_id' => 9],
            ['id' => 125, 'label' => 'Magoé', 'province_id' => 9],
            ['id' => 126, 'label' => 'Marara', 'province_id' => 9],
            ['id' => 127, 'label' => 'Marávia', 'province_id' => 9],
            ['id' => 128, 'label' => 'Moatize', 'province_id' => 9],
            ['id' => 129, 'label' => 'Mutarara', 'province_id' => 9],
            ['id' => 130, 'label' => 'Tete', 'province_id' => 9],
            ['id' => 131, 'label' => 'Tsangano', 'province_id' => 9],
            ['id' => 132, 'label' => 'Zumbo', 'province_id' => 9],
            ['id' => 133, 'label' => 'Alto Molócue', 'province_id' => 10],
            ['id' => 134, 'label' => 'Chinde', 'province_id' => 10],
            ['id' => 135, 'label' => 'Derre', 'province_id' => 10],
            ['id' => 136, 'label' => 'Gilé', 'province_id' => 10],
            ['id' => 137, 'label' => 'Gurué', 'province_id' => 10],
            ['id' => 138, 'label' => 'Ile', 'province_id' => 10],
            ['id' => 139, 'label' => 'Inhassunge', 'province_id' => 10],
            ['id' => 140, 'label' => 'Luabo', 'province_id' => 10],
            ['id' => 141, 'label' => 'Lugela', 'province_id' => 10],
            ['id' => 142, 'label' => 'Maganja da Costa', 'province_id' => 10],
            ['id' => 143, 'label' => 'Milange', 'province_id' => 10],
            ['id' => 144, 'label' => 'Mocuba', 'province_id' => 10],
            ['id' => 145, 'label' => 'Mocubela', 'province_id' => 10],
            ['id' => 146, 'label' => 'Molumbo', 'province_id' => 10],
            ['id' => 147, 'label' => 'Mopeia', 'province_id' => 10],
            ['id' => 148, 'label' => 'Morrumbala', 'province_id' => 10],
            ['id' => 149, 'label' => 'Mulevala', 'province_id' => 10],
            ['id' => 150, 'label' => 'Namacurra', 'province_id' => 10],
            ['id' => 151, 'label' => 'Namarroi', 'province_id' => 10],
            ['id' => 152, 'label' => 'Nicoadala', 'province_id' => 10],
            ['id' => 153, 'label' => 'Pebane', 'province_id' => 10],
            ['id' => 154, 'label' => 'Quelimane', 'province_id' => 10],
            ['id' => 155, 'label' => 'Distrito Urbano de KaMpfumo', 'province_id' => 11],
            ['id' => 156, 'label' => 'Distrito Urbano de Nlhamankulu', 'province_id' => 11],
            ['id' => 157, 'label' => 'Distrito Urbano de KaMaxaquene', 'province_id' => 11],
            ['id' => 158, 'label' => 'Distrito Urbano de KaMavota', 'province_id' => 11],
            ['id' => 159, 'label' => 'Distrito Urbano de KaMubukwana', 'province_id' => 11],
            ['id' => 160, 'label' => 'Distrito Municipal de KaTembe', 'province_id' => 11],
            ['id' => 161, 'label' => 'Distrito Municipal de KaNyaka', 'province_id' => 11]
        ]);
    }
}
